HPMC_PACK_SELECTED:
- PACK_CAT
HPMC_INPUT_SELECTED:
- INPUT_QTY
- INPUT_VIS_W
- INPUT_VIS_D
- INPUT_LOG_W
- INPUT_LOG_D
#- INPUT_MOISTURE
#- INPUT_BD
- INPUT_MEO
#- INPUT_HPO
#- INPUT_HEO
#- INPUT_ASH
HPMC_RE_INPUT_SELECTED:
- RE_INPUT_QTY
- RE_INPUT_VIS_W
- RE_INPUT_VIS_D
- RE_INPUT_LOG_W
- RE_INPUT_LOG_D
#- RE_INPUT_MOISTURE
#- RE_INPUT_BD
- RE_INPUT_MEO
#- RE_INPUT_HPO
#- RE_INPUT_HEO
#- RE_INPUT_ASH
HPMC_ADD_INPUT_SELECTED:
- CHUM_INPUT_QTY
- V_WEIGHTED
HPMC_TARGET_SELECTED:
- ITEM_RSLT
HEC_PACK_SELECTED:
- PACK_CAT
HEC_INPUT_SELECTED:
- INPUT_QTY
- INPUT_VIS_W
#- INPUT_VIS_D
- INPUT_LOG_W
#- INPUT_LOG_D
- INPUT_HYDROXYET
- INPUT_MS
- INPUT_MOISTURE
- INPUT_ASH
- INPUT_HYDRATION_TIME
- INPUT_PH
- INPUT_BD
- INPUT_YELLOWISH
- INPUT_BT
HEC_RE_INPUT_SELECTED:
- RE_INPUT_QTY
- RE_INPUT_VIS_W
#- RE_INPUT_VIS_D
- RE_INPUT_LOG_W
#- RE_INPUT_LOG_D
- RE_INPUT_HYDROXYET
- RE_INPUT_MS
- RE_INPUT_MOISTURE
- RE_INPUT_ASH
- RE_INPUT_HYDRATION_TIME
- RE_INPUT_PH
- RE_INPUT_BD
- RE_INPUT_YELLOWISH
- RE_INPUT_BT
HEC_ADD_INPUT_SELECTED:
- CHUM_INPUT_QTY
HEC_TARGET_SELECTED:
- ITEM_RSLT
