# LINEAR_REGRESSION: null
# RIDGE_REGRESSION: null
# RANDOM_FOREST:
#   HYPER_PARAMETERS:
#     N_ESTIMATORS: 120
# XGBOOST:
#   EARLY_STOPPING_ROUNDS: 20
#   EVAL_METRIC: mape
#   HYPER_PARAMETERS:
#     LEARNING_RATE: 0.005
#     N_ESTIMATORS: 5000
#     OBJECTIVE: reg:squarederror
#   VERBOSE: 10
